name: 🚀 Build Multi-Platform Apps

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Ручной запуск

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            name: Windows
            artifact: divergence-analyzer-windows.exe
            build_cmd: pyinstaller --onefile --windowed --name "DivergenceAnalyzer" divergence_analyzer_gui.py
          - os: macos-latest  
            name: macOS
            artifact: divergence-analyzer-macos
            build_cmd: pyinstaller --onefile --windowed --name "DivergenceAnalyzer" divergence_analyzer_gui.py
          - os: ubuntu-latest
            name: Linux
            artifact: divergence-analyzer-linux
            build_cmd: pyinstaller --onefile --name "DivergenceAnalyzer" divergence_analyzer_gui.py

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
    
    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib numpy pyinstaller
    
    - name: 📁 List files (Debug)
      run: |
        echo "=== Root directory ==="
        ls -la
        echo "=== Looking for Python files ==="
        find . -name "*.py" -type f
      shell: bash
    
    - name: 🔨 Build application (${{ matrix.name }})
      run: ${{ matrix.build_cmd }}
    
    - name: 📁 List dist contents (Debug)
      run: |
        echo "=== Dist directory contents ==="
        ls -la dist/
      shell: bash
    
    - name: 🏷️ Rename executable
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          mv dist/DivergenceAnalyzer.exe dist/${{ matrix.artifact }}
        else
          mv dist/DivergenceAnalyzer dist/${{ matrix.artifact }}
        fi
      shell: bash
    
    - name: ✅ Make executable (Unix)
      if: matrix.os != 'windows-latest'
      run: chmod +x dist/${{ matrix.artifact }}
    
    - name: 📦 Create DMG for macOS
      if: matrix.os == 'macos-latest'
      run: |
        # Создаем App Bundle структуру
        mkdir -p dist/DivergenceAnalyzer.app/Contents/MacOS
        mkdir -p dist/DivergenceAnalyzer.app/Contents/Resources
        
        # Копируем исполняемый файл
        cp dist/${{ matrix.artifact }} dist/DivergenceAnalyzer.app/Contents/MacOS/DivergenceAnalyzer
        chmod +x dist/DivergenceAnalyzer.app/Contents/MacOS/DivergenceAnalyzer
        
        # Создаем Info.plist
        cat > dist/DivergenceAnalyzer.app/Contents/Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>DivergenceAnalyzer</string>
            <key>CFBundleIdentifier</key>
            <string>com.zakat1191.divergenceanalyzer</string>
            <key>CFBundleName</key>
            <string>Divergence Analyzer</string>
            <key>CFBundleVersion</key>
            <string>1.0</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
        </dict>
        </plist>
        EOF
        
        # Создаем DMG
        hdiutil create -volname "Divergence Analyzer" -srcfolder dist/DivergenceAnalyzer.app -ov -format UDZO dist/DivergenceAnalyzer.dmg
        
        # Добавляем DMG к артефактам
        echo "DMG created: dist/DivergenceAnalyzer.dmg"
        ls -la dist/*.dmg
    
    - name: 📤 Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}-Build
        path: |
          dist/${{ matrix.artifact }}
          dist/*.dmg
        
    - name: 🎉 Build complete
      run: echo "✅ Build completed for ${{ matrix.name }}!"

# Убираем автоматические релизы - пока используем только артефакты
# После настройки прав можно будет включить обратно
